### PR TITLE
Extracts more logic out of AdminController into dedicated modules

### PR DESCRIPTION
**Pull request by baccigalupi**
CodeClimate with using the classic engine which checks complexity (and not just style) shows the AdminController as the top offender. Since that debt translates to real development costs, I took another stab at yanking out some logic and writing tests.

https://codeclimate.com/github/18F/midas/api/controllers/AdminController.js#all

Extracts logic for admin/taskMetrics into a series of modules:
        * DateDecorator for generating various sort codes based on a date string
        * DateCodeGenerator for generating the right code based on a
          group parameter
        * StateMetrics for aggregating task counts related to task
          states
        * TaskDecorator for generating task object decorated with
          additional state and date related data
        * VolunteerAgencyMetrics for doing additional searches and
          aggregating count data
        * Top level TaskMetrics object for taking needed data from the
          admin controller and generating metrics with the various
          detail classes.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Thanks for this PR @baccigalupi !

I'll take a look at this today and we can get it ready for our release this week.

**Comment by rogeruiz** [comment]
:+1: looks good. Thanks @baccigalupi !

**Comment by baccigalupi** [comment]
YAY!

Also, wanted to mention that the CodeClimate for the new repo name is only linting for style. Classic setup is still needed for Javascript to get cyclomatic complexity etc.

**Comment by rogeruiz** [comment]
Awesome. Thanks for letting me know about that @baccigalupi. I'll get it up and running to make sure it's set up properly.

**Pull request merged**
