### PR TITLE
Add ELK service

### LINKED ISSUE #1149: set up durable logging for new cf instances
we should be able to access historical logs for "openopps" apps in dev, staging, and prod 

https://github.com/18F/DevOps/issues/504

### PR DESCRIPTION
**Pull request by rogeruiz**
The ELK Service is set up on the `dev` space. In order for this to be merged successfully into production, I believe it's best to have the `ELK` service created and bound in each space before getting this in. This should close #1149 once it's merged.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Kibana is up and running. This branch needs to be deployed in order to be sure that the [`appmetrics-elk`](https://www.npmjs.com/package/appmetrics-elk) package is properly executing on the server.

**Without metrics package running, the data is there but isn't setup in the dashboards:**
screen shot 2015-11-25 at 11 33 41 am

**Comment by jeremiak** [comment]
@rogeruiz This looks super interesting and the `appmetrics-elk` package looks really promising. Interested to hear how it ends up, we might want to do this on Federalist too.

**Comment by rogeruiz** [comment]
The ELK service is setup on all three spaces for the app. I've also added the `credentials` hash to the Kibana Proxy app in CF. The PR includes some documentation around how to access the Kibana dashboard. Currently, Kibana isn't very useful because of a Logstash `_grokparsefailure` happening, but search filters can be used in Discover to still see some pretty neat analytics.

**Comment by rogeruiz** [comment]
Oh and @jeremiak I decided against using `appmetrics-elk` for now since I'd like to just track the syslog entries for now, but `appmetrics` would be great for data capturing without using Logstash I believe since it does the data-munging for you.

**Pull request merged**
